# 1 layer
FROM python:3.10-alpine3.15
LABEL author="kana.suzucki@gmail.com"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
ENV POETRY_VIRTUALENVS_CREATE=0

# 2 layer
RUN apk update && apk add bash curl postgresql-dev gcc g++ python3-dev musl-dev && pip install poetry

# 3 layer
WORKDIR /code
COPY pyproject.toml ./

# 4 layer
RUN poetry install --with prd

# 5 layer
COPY tlparser/src tlparser/scripts/entrypoint-uvicorn.prd.sh ./

# 6 layer
RUN chmod +x entrypoint-uvicorn.prd.sh